# Generated by Django 6.0.4 on 2026-05-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Kurs haqida malumot')),
                ('price', models.IntegerField(verbose_name='Kurs narxi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='course_images/', verbose_name='kurs rasmi')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Talaba ismi-fimiliyasi')),
                ('email', models.EmailField(max_length=254, verbose_name='Talaba email manzili')),
                ('phone', models.CharField(max_length=20, verbose_name='telfon raqami')),
                ('address', models.CharField(max_length=200, verbose_name='Yashash manzili')),
                ('courses', models.ManyToManyField(related_name='students', to='movie.course', verbose_name='yozilgan kurslar')),
                ('liked_courses', models.ManyToManyField(blank=True, related_name='likes', to='movie.course', verbose_name='Yoqtirgan kurslari')),
            ],
            options={
                'verbose_name': 'Talaba',
                'verbose_name_plural': 'Talabalar',
                'ordering': ['-id'],
            },
        ),
    ]
