# Generated by Django 6.0.4 on 2026-05-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Taqdim etilgan yili'),
        ),
        migrations.CreateModel(
            name='CourseLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.student')),
            ],
        ),
    ]
